### ISSUE TITLE
Image Perspective Transformation

### ISSUE THREAD

**Issue by hanrui234** [SokratG/Surround-View#13]
Sorry to bother you again, I saw that you have performed perspective transformation on the stitched image. Is the purpose of the perspective transformation to map with the bowl model? If so, why are the four coordinate points in the configuration file a very strange one? shape, thank you
The following code comes from SVStitcher.cpp

```
    WPTSfout["tl"] >> tl; WPTSfout["tr"] >> tr;
          WPTSfout["bl"] >> bl; WPTSfout["br"] >> br;
          WPTSfout["res_size"] >> resSize;
          const auto width_ = resSize.width;
          const auto height_ = resSize.height;


          std::vector<cv::Point_<float>> src {tl, tr, bl, br};
          std::vector<cv::Point_<float>> dst {cv::Point(0, 0), cv::Point(width_, 0),
                                              cv::Point(0, height_), cv::Point(width_, height_)};
          cv::Mat transformM = cv::getPerspectiveTransform(src, dst);

          cv::cuda::buildWarpPerspectiveMaps(transformM, false, resSize, warpXmap, warpYmap);

          row_range = cv::Range(tl.y, height_);
          col_range = cv::Range(0,  width_);
    }
```

**Comment by SokratG** [comment]
Hi! The idea is the following - tripod-mounted cameras have uneven heights(different heights). That mean I don't have pure rotation(it's strange because they don't have only rotation anyway, even if they are set at the same height), therefore I get much more offset of frames when I place them in one coordinate system(after calibration) and stitch.

Figure 1 (below) is an explanation of what this code does. I'm trying to find(automatically) 4 angle points of a stitched image ([code here](https://github.com/SokratG/Surround-View/blob/master/src/SVStitcher.cpp#L222)) and then I make perspective transform(warping) on full size of panorama figure 2. This is just texture preparing for pass to OpenGL and render on bowl mesh.

![figure 1](https://user-images.githubusercontent.com/39133972/222168200-8761c309-9b75-4913-a752-61e3082d2f83.png)

![figure 2](https://user-images.githubusercontent.com/39133972/222169298-c7f15602-f905-412d-8700-e7372ba47684.png)

**Comment by hanrui234** [comment]
Thanks for your answer, I got it
