### ISSUE TITLE
Hello, I have a problem. 

### ISSUE THREAD

**Issue by langmanman** [SokratG/Surround-View#16]
the result of my image splicing is correct, SVApp.cpp can see the result of splicing with the following code
svtitch->stitch(cameradata, stitch_frame);
cv::Mat stitched_frame;
stitch_frame.download(stitched_frame);
cv::imwrite("/usr/Surround-View-master/data/stitch.jpg", stitched_frame);
But execute this code in SVApp.cpp，The result displayed is only the car, no image after stitching
bool okRender = dp->render(stitch_frame);
![IMG_20230707_093254](https://github.com/SokratG/Surround-View/assets/137147455/74de3e67-fa52-41dc-95f8-a197a04e867c)
I put svrent.cpp in
auto ok = cuOgl.copyFrom(frame, 0);
Change into
auto ok = cuOgl.copyFrom(frame, 1);
Result display
![2023-07-07 09-42-10屏幕截图](https://github.com/SokratG/Surround-View/assets/137147455/90928cf5-1931-4e8f-816d-ad7da78b09cf)
Do you know what caused this
The opengl configuration is as follows

![2023-07-07 09-30-49屏幕截图](https://github.com/SokratG/Surround-View/assets/137147455/e4c0fcf2-aa63-4b17-a9e4-8118d69ed247)

**Comment by SokratG** [comment]
@langmanman Hello!
"I put svrent.cpp" what's svrent.cpp? What "stitched_frame" contains when You pass it to render? I mean type of data and steps. I think the problem may be in data type and step of the cv::cuda::GpuMat. Also OpenGL may require a different step value depending on GPU vendor and version. I tested only OpenGL ES 3.2.  About: 
"auto ok = cuOgl.copyFrom(frame, 0);
Change into
auto ok = cuOgl.copyFrom(frame, 1);"
The texture ID in glBindTexture must be 0 if you don't bind any other texture before/after in to current state for rendering.

**Comment by langmanman** [comment]
Thank you for your reply
svrent.cpp refers to svrent.cpp, I wrote it wrong, stitched_frame refers to code
svtitch->stitch(cameradata, stitch_frame);
After stitching the image stitch_frame, I saved it as jpg picture and found that it was correct, but the rendered result only showed the car without the stitched image. The opengl version I used was also 3.2, is it the problem of nvidia driver? Whether to use nvidia opengl or intel opengl

**Comment by langmanman** [comment]
The above image is the result of combining four pictures, the car is round under the car, and the result of using four cameras is square under the car
![微信图片_20230710175624](https://github.com/SokratG/Surround-View/assets/137147455/5abe0258-89d8-4756-a87c-926c1f16b4f3)

**Comment by SokratG** [comment]
> Thank you for your reply svrent.cpp refers to svrent.cpp, I wrote it wrong, stitched_frame refers to code svtitch->stitch(cameradata, stitch_frame); After stitching the image stitch_frame, I saved it as jpg picture and found that it was correct, but the rendered result only showed the car without the stitched image. The opengl version I used was also 3.2, is it the problem of nvidia driver? Whether to use nvidia opengl or intel opengl

Ok. As I said the problem in CUDA-OpenGL interoperability. Your texture which contain in "stitched_frame" not correctly pass to opengl buffer. I need more information about the data in stitched_frame:
![image](https://github.com/SokratG/Surround-View/assets/39133972/10143ba0-6d23-41db-89b5-4d6040bb1855)
The data type and step in your "stitched_frame".

But I'm sure the problem in OpenGL texture representation. I have tested only on **OpenGL ES 3.2** not in OpenGL 4.6. I think the problem not in driver of your GPU, on screenshot your drivers is correct. The data may be different stored in OpenGL 4.6.
  
1. Check stitched data representation(type and step). You can directly change the step value, because this is public field of cv::cuda::GpuMat
2. Check CUDA-OpenGL interoperability in [here](https://github.com/SokratG/Surround-View/blob/master/src/SVCudaOGL.cpp#L96), it may be need add some modifications for OpenGL 4.6.
3. For testing all render process is correctly work try to modify [here](https://github.com/SokratG/Surround-View/blob/master/shaders/surroundfrag.glsl#L85) FragColor variable with some random color. Also [here](https://github.com/SokratG/Surround-View/blob/master/shaders/surroundfrag.glsl#L22) could be a problem because I remember I tested the bowl render code on my laptop with OpenGL 4.6 and this part mostly suite for OpenGL ES 3.2. You can try to use just "highp vec3 color = vec3(texture(surroundTexture, textCoord));" 
4. I invert texture coordinate for correct render [here](https://github.com/SokratG/Surround-View/blob/master/shaders/surroundvert.glsl#L18). This is also needed only for OpenGL ES 3.2

**Comment by langmanman** [comment]
Thank you for your reply, the type and step information of stitich_frame is as follows
![微信图片_20230711102451](https://github.com/SokratG/Surround-View/assets/137147455/8d169afe-c891-4067-a9a8-0b7829785e1b)
highp vec4 color_a = vec4(color, 1.f);
highp vec3 color = vec3(texture(surroundTexture, textCoord));
I modified the above two code results are unchanged

**Comment by langmanman** [comment]
My opengl version is 4.6 and opengl es version is 3.2. Are both of your versions 3.2
![251614175-e4c0fcf2-aa63-4b17-a9e4-8118d69ed247](https://github.com/SokratG/Surround-View/assets/137147455/9220346c-61a7-4fa6-b22b-dd24b38f2cb2)

**Comment by langmanman** [comment]
> Thank you for your reply, the type and step information of stitich_frame is as follows ![微信图片_20230711102451](https://user-images.githubusercontent.com/137147455/252533593-8d169afe-c891-4067-a9a8-0b7829785e1b.jpg) 
I changed the following two code, and the result is not changed.
(1)highp vec4 color_a = vec4(color, 1.f); 
I changed 1.f to something else.
(2)highp vec3 color = vec3(texture(surroundTexture, textCoord)); 
![微信图片_20230711112510](https://github.com/SokratG/Surround-View/assets/137147455/857eb158-9e7e-4eeb-8c9b-fe29bab6813c)
I modified the above two code results are unchanged

**Comment by langmanman** [comment]
Thank you for your reply, the type and step information of stitich_frame is as follows.
![252533593-8d169afe-c891-4067-a9a8-0b7829785e1b](https://github.com/SokratG/Surround-View/assets/137147455/f1c6a23c-9412-4db5-847c-efc1842eb370)
I changed the following two code, and the result is not changed.
(1)highp vec4 color_a = vec4(color, 1.f);
I changed 1.f to something else.
(2)highp vec3 color = vec3(texture(surroundTexture, textCoord));
![252542544-857eb158-9e7e-4eeb-8c9b-fe29bab6813c](https://github.com/SokratG/Surround-View/assets/137147455/debd9fb2-1c77-4dc3-bc71-064a87e66ebe)
I modified the above two code results are unchanged

**Comment by SokratG** [comment]
The step is strange...What the resolution of your stitched_image? Because it must be equal the width. The type is wrong the 19 it's CV_16S but it should be 16 or CV_8UC3, see [here](https://gist.github.com/pabloduque0/456cb62d02a027d3a458f31cdec6771d) because your prepare opengl buffer with 3 channels by 8 bits ([here](https://github.com/SokratG/Surround-View/blob/master/src/SVCudaOGL.cpp#L56)).

In addition, you misunderstood my suggestions to change part of the code in shader programs, please re-read carefully.

**Comment by langmanman** [comment]
I set stitch_frame to read an image, and then look at stitich_frame type and step, again only show the car, using the image and the result is as follows

![stitch_frame](https://github.com/SokratG/Surround-View/assets/137147455/e379fe9b-2d35-458f-9668-234826b24734)

![2023-07-14 10-40-11屏幕截图](https://github.com/SokratG/Surround-View/assets/137147455/3f9897bb-2445-43f9-8263-80b81b9bb586)
As for the opengl version you mentioned, my opengl es version is also 3.2, is it the same with yours?

**Comment by langmanman** [comment]
I changed the version of opengl, the version information is as follows, and I get the same result, only the car can be seen
![2023-07-18 15-33-50屏幕截图](https://github.com/SokratG/Surround-View/assets/137147455/8c2aaba3-6ed9-49f7-a803-81818012c872)

**Comment by SokratG** [comment]
I think the problem not in version of OpenGL ES. My guess the problem inside CUDA-OpenGL interoperability. You can try store stitched image in host memory and then try to load into OpenGL texture memory [here](https://github.com/SokratG/Surround-View/blob/master/src/SVRender.cpp#L73) and example how you can do this [here](https://learnopengl.com/Getting-started/Textures). It's just to understand where the problem is.

**Comment by w-w-p** [comment]
Hello, I have the same problem. How can I solve it?
